### PR TITLE
Update map4.OCM

### PR DESCRIPTION
**Pull request by anilkunwar**
The filename for the thermodynamic database has block letters for Oxygen and Uranium and so the executable oc3B can read it when it is written as `r t OU`.

### CODE REVIEW

**Comment by sundmanbo** [comment]
Hi Anil
I do not understand this message?  OC is in most cases insensitive to the case
/Bosse
 *** Please do not make reply to this yahoo mail : Send messages to bo.sundman@gmail.com  *** 

    On Friday, March 25, 2016 10:05 PM, Anil Kunwar <notifications@github.com> wrote:
 

 The filename for the thermodynamic database has block letters for Oxygen and Uranium and so the executable oc3B can read it when it is written as r t OU.
You can view, comment on, or merge this pull request online at:
  https://github.com/sundmanbo/opencalphad/pull/28
Commit Summary
   
   - Update map4.OCM

File Changes
   
   -  M macros/ocv3/map4.OCM (2) 

Patch Links:
   
   - https://github.com/sundmanbo/opencalphad/pull/28.patch
   - https://github.com/sundmanbo/opencalphad/pull/28.diff

**Comment by anilkunwar** [comment]
Hi Bosse Sir,
I am running OpenCalphad through Ubuntu 14.04 interface. In my opinion accessing files within a computer by a software is dependent on the location of the file with designated filename.Ubuntu is case sensitive in terms of the directory and file names. So,it makes distinctions between block and small letters. Windows system is case insensitive and it will read both OU and ou as same.

Yours Sincerely,
Anil Kunwar

**Comment by sundmanbo** [comment]
Hi Anil
I know that but as this an OS feature you should mention that.
/Bosse
  *** Please do not make reply to this yahoo mail : Send messages to bo.sundman@gmail.com  *** 

    On Saturday, March 26, 2016 12:12 PM, Anil Kunwar <notifications@github.com> wrote:
 

 Hi Bosse Sir,
I am running OpenCalphad through Ubuntu 14.04 interface. In my opinion accessing files within a computer by a software is dependent on the location of the file with designated filename.Ubuntu is case sensitive in terms of the directory and file names. So,it makes distinctions between block and small letters. Windows system is case insensitive and it will read both OU and ou as same.Yours Sincerely,
Anil Kunwar —

**Comment by anilkunwar** [comment]
Hi Bosse sir,
I am sorry for my unclear comment on the changes made. However, since OC is a very strong software, we need to make sure it finds compatibility with several OS. As windows is case insensitive to file names and linux is, i request you to ensure that the file reading by the software follows the linux pattern as windows will automatically accept in any format owing to it case insensitiveness. I find OpenCalphad a very strong learning tool for computational thermodynamics. I admire your tireless efforts.

Yours Sincerely,
Anil Kunwar

**Pull request closed without merging**
